// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknzPxAyOWd-rfFjO1QwObcY09QfxjcV8',
    appId: '1:867386599382:web:dec93467ae7f59e8d32677',
    messagingSenderId: '867386599382',
    projectId: 'tailor-app-8f409',
    authDomain: 'tailor-app-8f409.firebaseapp.com',
    storageBucket: 'tailor-app-8f409.firebasestorage.app',
    measurementId: 'G-R4JG32Z3TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHFpYyn7kNSKKccZOZQnT4ozec1OCSQw',
    appId: '1:867386599382:android:cc7e1b5c5bca835cd32677',
    messagingSenderId: '867386599382',
    projectId: 'tailor-app-8f409',
    storageBucket: 'tailor-app-8f409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMJiFEvL6Gir6LlxOOPs3p-YX3IYZSZo',
    appId: '1:867386599382:ios:df5101269897b395d32677',
    messagingSenderId: '867386599382',
    projectId: 'tailor-app-8f409',
    storageBucket: 'tailor-app-8f409.firebasestorage.app',
    iosBundleId: 'com.tailorapp.tailorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgMJiFEvL6Gir6LlxOOPs3p-YX3IYZSZo',
    appId: '1:867386599382:ios:df5101269897b395d32677',
    messagingSenderId: '867386599382',
    projectId: 'tailor-app-8f409',
    storageBucket: 'tailor-app-8f409.firebasestorage.app',
    iosBundleId: 'com.tailorapp.tailorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCknzPxAyOWd-rfFjO1QwObcY09QfxjcV8',
    appId: '1:867386599382:web:dec93467ae7f59e8d32677',
    messagingSenderId: '867386599382',
    projectId: 'tailor-app-8f409',
    storageBucket: 'tailor-app-8f409.firebasestorage.app',
  );
}
