// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhwP5TEySO_19hMeqmKMOoXFdNP3xLfws',
    appId: '1:941714203649:web:1a4b7fa9b369c845548c00',
    messagingSenderId: '941714203649',
    projectId: 'tailor-app-7e9e7',
    authDomain: 'tailor-app-7e9e7.firebaseapp.com',
    storageBucket: 'tailor-app-7e9e7.firebasestorage.app',
    measurementId: 'G-V03XK42YDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHFpYyn7kNSKKccZOZQnT4ozec1OCSQw',
    appId: '1:867386599382:android:cc7e1b5c5bca835cd32677',
    messagingSenderId: '867386599382',
    projectId: 'tailor-app-8f409',
    storageBucket: 'tailor-app-8f409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7bfjpKoG-P7Ukgu9QUed5FOXfY9O5Upg',
    appId: '1:941714203649:ios:88a22d875b69022d548c00',
    messagingSenderId: '941714203649',
    projectId: 'tailor-app-7e9e7',
    storageBucket: 'tailor-app-7e9e7.firebasestorage.app',
    iosBundleId: 'com.tailorapp.tailorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7bfjpKoG-P7Ukgu9QUed5FOXfY9O5Upg',
    appId: '1:941714203649:ios:88a22d875b69022d548c00',
    messagingSenderId: '941714203649',
    projectId: 'tailor-app-7e9e7',
    storageBucket: 'tailor-app-7e9e7.firebasestorage.app',
    iosBundleId: 'com.tailorapp.tailorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaHFpYyn7kNSKKccZOZQnT4ozec1OCSQw',
    appId: '1:867386599382:android:cc7e1b5c5bca835cd32677',
    messagingSenderId: '867386599382',
    projectId: 'tailor-app-8f409',
    storageBucket: 'tailor-app-8f409.firebasestorage.app',
  );
}
